add physical package object to definitions
edatasheets/digital-datasheets pull request #13
Opened 2022-06-15 14:15 UTC by rsnancollas

package definition draft for passives as well as generally for all components

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +          "centimeter"
remove centimeter

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +          "inches",
maybe remove inches

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +      "standardPackageType": {
standardPackageSize

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +        ]
standardPackageType:

examples:
BGA
TSSOP

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +        "enum": [
examples, not enum

2022-06-15 15:42 UTC, rsnancollas commented on part-spec/definitions.json
> +        "description": "name of standard package type (imperial)",
standard package size

2022-06-23 17:58 UTC, rsnancollas commented
Added a new commit - ready for review

2022-06-23 23:18 UTC, asadate requested changes

2022-06-23 23:18 UTC, asadate commented on part-spec/definitions.json
> +          "milimeter"
typo: millimeter

2022-06-24 18:11 UTC, rsnancollas commented
Typo fixed and ready for review

2022-06-24 19:52 UTC, asadate commented on part-spec/definitions.json
> +          "milimeter"
Not sure why I can't see the change. It still shows "milimeter"

2022-06-28 15:18 UTC, asadate approved these changes

2022-06-28 15:31 UTC, merged