initial draft of mosfet in semiconductor.json for spec v0.7
edatasheets/digital-datasheets pull request #19
Opened 2022-07-27 02:06 UTC by rsnancollas

A little late, but here is an initial draft of the mosfet spec based on our discussion from a few meetings ago.

2022-08-11 05:06 UTC, asadate requested changes

2022-08-11 05:06 UTC, asadate commented on part-spec/semiconductor.json
> +                "datasheetVersion",
required should be componentID + the other 2 properties

2022-08-11 05:06 UTC, asadate commented on part-spec/semiconductor.json
> +                    "description": "maximum gate to source voltage difference required to produce a conducting path between drain and source",
Should we change this to vgsThresholdMax?

2022-09-16 17:23 UTC, asadate reviewed
Changes requested by Nexperia were added.

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                    "comment": "units of amps",
"forward current of the device"  instead of " forward current of a diode."

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                    "description": "whether a diode has built in esd protection",
esdProtection property not needed

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                }
Missing properties: Number of diodes, Number of protected lines, Configuration

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                    ],
add nAndpType in the enum list

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                    ],
changed

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                    "comment": "units of amps",
Changes will be done in a future revision. Updating now will require us to go update all the other component datasheets already released.

2022-09-16 17:23 UTC, asadate commented on part-spec/semiconductor.json
> +                }
Added

2022-09-30 16:52 UTC, asadate commented on part-spec/definitions.json
> +    "type": "object",
Will remove "min", "max", "typ", from here and replace with "value" following up WG discussion to call out minValue,..maxValue as different properties.

2022-10-18 22:10 UTC, Carrotman42 approved these changes
I took a look and everything seems OK. To me, that implies that maybe I don't have the ability to give a good review here ;)

But you can at least count this as a looks-good-to-kevin.

2022-10-19 00:02 UTC, asadate approved these changes
Requested changes implemented

2022-10-19 00:02 UTC, asadate commented on support-docs/examples.md
> +        "conditions": ["forward current (If)=800mA"]
Add JSON format easy to parse

2022-10-19 00:02 UTC, merged