add BJT and make changes to support ESD array
edatasheets/digital-datasheets pull request #56
Opened 2023-05-12 19:15 UTC by rsnancollas

This commit adds a BJT definition to semiconductor.json and changes the diode definition to support an ESD array.

2023-05-16 02:24 UTC, asadate requested changes

2023-05-16 02:24 UTC, asadate commented on part-spec/semiconductor.json
> +                    "$comment": "units of amps",
Overall comments for all the parameters here. Since they're pretty much standard should we use them? for example "iCC" instead of collectorCurrent? Let's discuss.

2023-05-16 02:24 UTC, asadate commented on part-spec/semiconductor.json
> +                    "description": "collector-emitter voltage below with a change in base current does not impact collector current (VCE_SAT)",
Typo: below "which"

2023-05-16 02:24 UTC, asadate commented on part-spec/semiconductor.json
> +                "peakBaseCurrent": {
base current ib missing?

2023-05-16 02:24 UTC, asadate commented on part-spec/semiconductor.json
> +                },
We may also want to add the Collector-Emitter and the Collector-Base breakdown voltages.

2023-05-20 00:42 UTC, rsnancollas commented on part-spec/semiconductor.json
> +                    "$comment": "units of amps",
I wasn't sure. We've done some of both. We should probably discuss in the working group and decide on a standard across the board.

2023-05-20 00:45 UTC, rsnancollas commented on part-spec/semiconductor.json
> +                    "$comment": "units of amps",
I added it to the agenda for next meeting.

2023-05-20 00:49 UTC, rsnancollas commented
I ended up having to start a new PR to fix merge conflicts, but I resolved all your comments.

2023-05-20 00:49 UTC, closed without merging